name: Publish Python 🐍 packages 📦 to PyPI
on:
  push:
    tags:
      - 'v?[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-n-publish:
    name: Build and publish Python 🐍 packages 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build a binary wheel and a source tarball
      run: python setup.py sdist

    - name: Publish package 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.5.0
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
